{
 "title": "SPIRL Trust Domain Server",
 "tags": [ "spirl" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,15m,30m,1h" },
   {
    "name": "spirl_trust_domain",
    "label": "SPIRL Trust Domain",
    "query": {
     "query": "label_values({spirl_component=\"server\"},spirl_trust_domain)"
    }
   },
   {
    "name": "spirl_trust_domain_deployment",
    "label": "SPIRL Trust Domain Deployment",
    "query": {
     "query": "label_values({spirl_trust_domain=\"$spirl_trust_domain\", spirl_component=\"server\"},spirl_trust_domain_deployment)"
    }
   },
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "label_values({spirl_trust_domain=\"$spirl_trust_domain\", spirl_trust_domain_deployment=~\"$spirl_trust_domain_deployment\", spirl_component=\"server\"},${pod_label})"
    }
   },
   { "name": "pod_label", "label": "Pod Label", "query": "pod,k8s_pod_name" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Success",
   "type": "stat",
   "description": "Shows the successful API call percentage of all APIs exposed by the server.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (\n    (\n        sum(\n            rate(\n                grpc_server_handled_total{\n                    ${pod_label}=~\"$pods\", \n                    grpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\", \n                    grpc_code!=\"OK\", \n                    grpc_code!=\"Canceled\",\n                    grpc_code!=\"NotFound\"\n                    }[$interval]\n                )\n            )\n        ) \n        / \n        clamp_min(\n            sum(\n                rate(\n                    grpc_server_handled_total{\n                        ${pod_label}=~\"$pods\", \n                        grpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\"\n                    }[$interval]\n                )\n            ), 0.001\n        )\n    )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (p95)",
   "type": "stat",
   "description": "The 95th percentile response time (considering all APIs). Represents the maximum latency experienced by 95% of requests, measured in seconds.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\",\ngrpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per second. Shows the current throughput of all API calls being handled by server.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{${pod_label}=~\"$pods\", grpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\", grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Trust Domain Deployment Versions",
   "type": "table",
   "description": "Displays the current version information for each trust domain deployment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by (spirl_trust_domain, spirl_trust_domain_deployment, spirl_app_version) (spirl_application_info{${pod_label}=~\"$pods\", spirl_component=\"server\", spirl_trust_domain!=\"\"})"
    }
   ]
  },
  { "title": "Resources Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network Bandwidth - Received",
   "type": "timeseries",
   "description": "Shows network traffic received by each pod, measured in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pods\", pod!=\"\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth - Transmitted",
   "type": "timeseries",
   "description": "Shows network traffic transmitted by each pod, measured in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$pods\", pod!=\"\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "description": "Current CPU utilization for each pod, measured in CPU cores.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$pods\", container!=\"\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "timeseries",
   "description": "Current memory usage for each pod, measured in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container!=\"\", pod=~\"$pods\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods CPU Limit",
   "type": "timeseries",
   "description": "Maximum allocated CPU cores for each pod based on resource limits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Memory Limit",
   "type": "timeseries",
   "description": "Maximum allocated memory for each pod based on resource limits.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods CPU Usage Limit",
   "type": "bargauge",
   "description": "Percentage of CPU usage compared to the pod limit. Values approaching red indicate pods nearing their CPU resource limits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pods\", container!=\"\"}[$interval])) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Memory Usage Limit",
   "type": "bargauge",
   "description": "Percentage of memory usage compared to the pod limit. Values approaching red indicate pods nearing their memory resource limits.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pods\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM Events",
   "type": "stat",
   "description": "Out of Memory events count. Shows how many times pods have been terminated due to memory limits being exceeded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_oom_events_total{pod=~\"$pods\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Service Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Response Time (p99)",
   "type": "timeseries",
   "description": "The 99th percentile response time. Represents the maximum latency experienced by 99% of requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\",\ngrpc_method!=\"SyncTrustBundles\"\n}[$interval])) by (grpc_method,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Response Time (p90)",
   "type": "timeseries",
   "description": "The 90th percentile response time. Represents the maximum latency experienced by 90% of requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\",\ngrpc_method!=\"SyncTrustBundles\"\n}[$interval])) by (grpc_method,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Response Time (p50)",
   "type": "timeseries",
   "description": "The 50th percentile (median) response time. Represents the typical latency experienced by most requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\",\ngrpc_method!=\"SyncTrustBundles\"\n}[$interval])) by (grpc_method,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Streaming Ops Throughput",
   "type": "timeseries",
   "description": "Rate of messages sent and received through streaming operations, showing the bidirectional traffic volume.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{\n  ${pod_label}=~\"$pods\",\n  grpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\",\n  grpc_type=~\"server_stream|bidi_stream\"\n}[$interval])) by (grpc_method)\n",
     "legendFormat": "{{grpc_method}}-sent"
    },
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{\n  ${pod_label}=~\"$pods\",\n  grpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\",\n  grpc_type=~\"server_stream|bidi_stream\"\n}[$interval])) by (grpc_method)\n",
     "legendFormat": "{{grpc_method}}-received"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per second. Shows the current throughput of API calls being handled by RPC.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{\n    ${pod_label}=~\"$pods\",\n    grpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\"}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Percentage of API calls resulting in errors. Lower values indicate better service health.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\",\ngrpc_code!=\"OK\",\ngrpc_code!=\"Canceled\"}[$interval])) by (grpc_method) /\nclamp_min(sum(rate(grpc_server_handled_total{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.agent.v1.agent.API|com.spirl.agent.v1.session.API\"}[$interval])) by(grpc_method), 0.001)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Control Plane Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Percentile response time. Represents the maximum latency experienced by\n100%, 99%, 95% and 50% of requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\"\n}[$interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\"\n}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\"\n}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\"\n}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per second made to the control plane. Shows the current throughput of API calls being handled by RPC.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{\n    ${pod_label}=~\"$pods\",\n    grpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\"}[$interval]))",
     "legendFormat": "Requests Per Second"
    }
   ]
  },
  {
   "title": "Errors by RPC code",
   "type": "timeseries",
   "description": "API calls to the control plane resulting in errors by error code. Lower values indicate better service health.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum by(grpc_code) (increase(grpc_server_handled_total{${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\", grpc_code != \"OK\"}[$interval])) > 0",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Percentage of API calls to the control plane resulting in errors. Lower values indicate better connectivity health.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\",\ngrpc_code!=\"OK\",\ngrpc_code!=\"Canceled\"}[$interval])) /\nclamp_min(sum(rate(grpc_server_handled_total{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"com.spirl.private.signer.api.v1.configuration.API|com.spirl.private.signer.api.v1.regionauthority.API|com.spirl.private.signer.api.v1.federation.API\"}[$interval])), 0.001)\n",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}