{
 "title": "SPIRL Trust Domain Agents",
 "tags": [ "spirl" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   {
    "name": "spirl_trust_domain",
    "label": "spirl_trust_domain",
    "query": {
     "query": "label_values({spirl_component=\"agent\"},spirl_trust_domain)"
    }
   },
   {
    "name": "spirl_trust_domain_deployment",
    "label": "spirl_trust_domain_deployment",
    "query": {
     "query": "label_values({spirl_trust_domain=\"$spirl_trust_domain\", spirl_component=\"agent\"},spirl_trust_domain_deployment)"
    }
   },
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "label_values({spirl_trust_domain=\"$spirl_trust_domain\", spirl_trust_domain_deployment=~\"$spirl_trust_domain_deployment\", spirl_component=\"agent\"},${pod_label})"
    }
   },
   { "name": "pod_label", "label": "Pod Label", "query": "pod,k8s_pod_name" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Success",
   "type": "stat",
   "description": "Shows the successful API call percentage of all APIs exposed by the agent.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - ((sum(rate(grpc_server_handled_total{${pod_label}=~\"$pods\", grpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\", grpc_code!=\"OK\", grpc_code!=\"Canceled\"}[$interval]))) / clamp_min(sum(rate(grpc_server_handled_total{${pod_label}=~\"$pods\", grpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\"}[$interval])), 0.001))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (p95)",
   "type": "stat",
   "description": "The 95th percentile response time (considering all APIs). Represents the maximum latency experienced by 95% of requests, measured in seconds.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(spirl_agent_mint_svid_duration_seconds_bucket{\n${pod_label}=~\"$pods\"}[$interval])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per second. Shows the current throughput of all API calls being handled by agent.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{${pod_label}=~\"$pods\", grpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\", grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Trust Domain Deployment Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by (spirl_trust_domain, spirl_trust_domain_deployment, spirl_app_version) (spirl_application_info{${pod_label}=~\"$pods\", spirl_component=\"agent\", spirl_trust_domain!=\"\"})"
    }
   ]
  },
  { "title": "Resources Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network Bandwidth Transmitted",
   "type": "timeseries",
   "description": "Network bandwidth transmitted by each pod, measured in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_network_transmit_bytes_total{pod=~\"$pods\", pod!=\"\"}[$interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bandwidth Received",
   "type": "timeseries",
   "description": "Network bandwidth received by each pod, measured in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_network_receive_bytes_total{pod=~\"$pods\", pod!=\"\"}[$interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "description": "Current CPU usage for each pod, measured in CPU cores.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$pods\", container!=\"\"}[$interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "timeseries",
   "description": "Current memory usage for each pod, measured in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container!=\"\", pod=~\"$pods\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods CPU Limit",
   "type": "timeseries",
   "description": "Displays the CPU limit configured for each pod, measured in CPU cores. This is the maximum CPU resources that can be allocated to the pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Memory Limit",
   "type": "timeseries",
   "description": "Shows the memory limit configured for each pod, measured in bytes. This is the maximum memory that can be allocated to the pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"memory\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods CPU Usage Limit",
   "type": "bargauge",
   "description": "Percentage of CPU usage compared to the pod limit. Values approaching red indicate pods nearing their CPU resource limits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pods\", container!=\"\"}[$interval])) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Memory Usage Limit",
   "type": "bargauge",
   "description": "Percentage of memory usage compared to the pod limit. Values approaching red indicate pods nearing their memory resource limits.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pods\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"$pods\", container!=\"\", resource=\"memory\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOM Events",
   "type": "stat",
   "description": "Out of Memory events count. Shows how many times pods have been terminated due to memory limits being exceeded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_oom_events_total{pod=~\"$pods\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Service Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Response Time (p99)",
   "type": "timeseries",
   "description": "The 99th percentile response time. Represents the maximum latency experienced by 99% of requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\",\ngrpc_type=\"unary\"}[$interval])) by (grpc_method,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Response Time (p90)",
   "type": "timeseries",
   "description": "The 90th percentile response time. Represents the maximum latency experienced by 90% of requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\",\ngrpc_type=\"unary\"}[$interval])) by (grpc_method,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Response Time (p50)",
   "type": "timeseries",
   "description": "The median (50th percentile) response time. Represents the typical latency experienced by requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum(rate(grpc_server_handling_seconds_bucket{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\",\ngrpc_type=\"unary\"}[$interval])) by (grpc_method,le))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Streaming Ops Throughput",
   "type": "timeseries",
   "description": "Shows the throughput of streaming operations, displaying both sent and received messages per second.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{\n  ${pod_label}=~\"$pods\",\n  grpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\",\n  grpc_type=~\"server_stream|bidi_stream\"\n}[$interval])) by (grpc_method)\n",
     "legendFormat": "{{grpc_method}}-sent"
    },
    {
     "expr": "sum(rate(grpc_server_msg_received_total{\n  ${pod_label}=~\"$pods\", \n  grpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\", \n  grpc_type=~\"client_stream|bidi_stream\"\n}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}-received"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Shows the Requests Per Second (RPS) rate for each gRPC method, broken down by service.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{${pod_label}=~\"$pods\", grpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\", grpc_type=\"unary\"}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Shows the percentage of failed gRPC API calls for each method. Calculated as the ratio of non-OK and non-Canceled responses to total responses.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\",\ngrpc_code!=\"OK\",\ngrpc_code!=\"Canceled\"}[$interval])) by (grpc_method) /\nclamp_min(sum(rate(grpc_server_handled_total{\n${pod_label}=~\"$pods\",\ngrpc_service=~\"SpiffeWorkloadAPI|envoy.service.secret.v3.SecretDiscoveryService\"}[$interval])) by(grpc_method), 0.001)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}