{
 "title": "Workloads Credential Rotation",
 "tags": [
  "spirl",
  "envoy"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(envoy_sds_default_control_plane_connected_state,namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"},app)"
    }
   },
   {
    "name": "pods",
    "label": "pods",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", app=~\"$app\"},pod)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "WLAPI Connection State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_sds_default_control_plane_connected_state{pod=~\"$pods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": " Certificate Update Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_sds_default_update_failure{pod=~\"$pods\"}[$interval])) by(pod) / \nclamp_min(sum(rate(envoy_sds_default_update_attempt{pod=~\"$pods\"}[$interval])) by(pod), 0.0001)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Key Rotation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(envoy_sds_default_key_rotation_failed{pod=~\"$pods\"}[$interval])) by(pod)",
     "legendFormat": "{{pod}}attempt"
    }
   ]
  },
  {
   "title": "Certificate Update Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_sds_default_update_duration_bucket{pod=~\"$pods\"}[$interval])) by (le, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Certificate Update Latency (p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_sds_default_update_duration_bucket{pod=~\"$pods\"}[$interval])) by (le, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Certificate Update Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(envoy_sds_default_update_duration_bucket{pod=~\"$pods\"}[$interval])) by (le, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}